name: cachix
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: cachix/install-nix-action@v18
    - uses: cachix/cachix-action@v12
      with:
        name: godot
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: 'echo ${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build -L .#godot-master
